# pyproject.toml

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.11"]

[project]
name = "davotools"
description = "DavoLatte's Everyday Tools"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
]
authors = [
  { name="Jihwan Oh", email="jihwan05us@gmail.com" },
]
maintainers = [
  { name="Jihwan Oh", email="jihwan05us@gmail.com" },
]
version = "0.3.1"
requires-python = ">=3.10"
dependencies = [
    "geojson",
    "ipython",
    "matplotlib",
    "numpy",
    "pandas",
    "pyarrow",
    "pyyaml",
    "scikit-image",
    "shapely",
    "tifffile",
    "tqdm",
]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/jihwan05us/davotools"
Issues = "https://github.com/jihwan05us/davotools/issues"
